export const parentNav = [
  {
    id: 1,
    name: 'Dashboard',
    route: '/parent',
    value: 'dashboard',
    icon: '/images/dash.svg',
    active: '/images/dash-active.svg',
  },
  {
    id: 2,
    name: 'My Wards',
    route: '/parent/wards',
    value: 'wards',
    icon: '/images/wards.svg',
    active: '/images/ward-active.svg',
  },
  {
    id: 3,
    name: 'Courses',
    value: 'courses',
    route: '/parent/courses',
    icon: '/images/course.svg',
    active: '/images/course-active.svg',
  },
  {
    id: 4,
    name: 'Payment',
    value: 'payment',
    route: '/parent/payment',
    icon: '/images/pay.svg',
    active: '/images/pay-active.svg',
  },
  {
    id: 5,
    name: 'Resources',
    route: 'resources',
    value: 'resources',
    icon: '/images/resource.svg',
    active: '/images/resource-active.svg',
  },
  {
    id: 6,
    name: 'Support',
    value: 'support',
    route: '/parent/support',
    icon: '/images/support.svg',
    active: '/images/support-active.svg',
  },
  {
    id: 7,
    name: 'My Account',
    value: 'account',
    route: '/parent/account',
    icon: '/images/account.svg',
    active: '/images/account-active.svg',
  },
];
export const lineData = [
  {
    name: 'Page A',
    uv: 4000,
    pv: 2400,
    amt: 2400,
  },
  {
    name: 'Page B',
    uv: 3000,
    pv: 1398,
    amt: 2210,
  },
  {
    name: 'Page C',
    uv: 2000,
    pv: 9800,
    amt: 2290,
  },
  {
    name: 'Page D',
    uv: 2780,
    pv: 3908,
    amt: 2000,
  },
  {
    name: 'Page E',
    uv: 1890,
    pv: 4800,
    amt: 2181,
  },
  {
    name: 'Page F',
    uv: 2390,
    pv: 3800,
    amt: 2500,
  },
  {
    name: 'Page G',
    uv: 3490,
    pv: 4300,
    amt: 2100,
  },
];

export const data = [
  { day: 'Sunday', Jacob: 54, Sarah: 30 },
  { day: 'Monday', Jacob: 42, Sarah: 25 },
  { day: 'Tuesday', Jacob: 75, Sarah: 60 },
  { day: 'Wednesday', Jacob: 110, Sarah: 70 },
  { day: 'Thursday', Jacob: 23, Sarah: 15 },
  { day: 'Friday', Jacob: 87, Sarah: 60 },
  { day: 'Saturday', Jacob: 50, Sarah: 30 },
];
export const coursesArray = [
  {
    title: 'Mathematics - K2 to K5 level, (Basic Mathematics)',
    description: 'Basic Mathematics',
    imageSrc: '/images/course-1.svg',
    duration: '5 - 7 hours',
    learners: 547,
  },
  {
    title: 'Mathematics - K2 to K5 level, (Intermediate Mathematics)',
    description: 'Intermediate Mathematics',
    imageSrc: '/images/course-2.svg',
    duration: '5 - 7 hours',
    learners: 547,
  },
  {
    title: 'Mathematics - K2 to K5 level, (Advanced Mathematics)',
    description: 'Advanced Mathematics',
    imageSrc: '/images/course-3.svg',
    duration: '5 - 7 hours',
    learners: 547,
  },
  {
    title: 'Mathematics - K6 to K12 level, (Basic Mathematics)',
    description: 'Basic Mathematics',
    imageSrc: '/images/course-4.svg',
    duration: '5 - 7 hours',
    learners: 547,
  },
  {
    title: 'Mathematics - K6 to K12 level, (Intermediate Mathematics)',
    description: 'Intermediate Mathematics',
    imageSrc: '/images/course-5.svg',
    duration: '5 - 7 hours',
    learners: 547,
  },
  {
    title: 'Mathematics - K2 to K5 level, (Intermediate Mathematics)',
    description: 'Intermediate Mathematics',
    imageSrc: '/images/course-2.svg',
    duration: '5 - 7 hours',
    learners: 547,
  },
];
export const pricingData: any[] = [
  {
    title: 'Basic Plan',
    price: '£10',
    period: '/ month',
    features: [
      { feature: 'Access to selected free courses.', available: true },
      { feature: 'Limited course materials.', available: true },
      { feature: 'No certification upon completion.', available: false },
      { feature: 'Ad-supported platform.', available: false },
      { feature: 'Access to exclusive Pro Plan.', available: false },
      { feature: 'Early access to new courses.', available: false },
    ],
    buttonVariant: 'solid',
    buttonColorScheme: '#0A52A8',
    bgColor: '#F2F2F2',
    textColor: 'black',
    buttonText: '#fff',
  },
  {
    title: 'Standard Plan',
    price: '£20',
    period: '/ month',
    features: [
      { feature: 'Access to selected free courses.', available: true },
      { feature: 'Limited course materials.', available: true },
      { feature: 'No certification upon completion.', available: true },
      { feature: 'Ad-supported platform.', available: true },
      { feature: 'Access to exclusive Pro Plan.', available: false },
      { feature: 'Early access to new courses.', available: false },
    ],
    isPopular: true,
    buttonVariant: 'solid',
    buttonColorScheme: 'white',
    bgColor: '#FBA333',
    textColor: 'white',
    buttonText: '#0A52A8',
  },
  {
    title: 'Premium Plan',
    price: '£50',
    period: '/ month',
    features: [
      { feature: 'Access to selected free courses.', available: true },
      { feature: 'Limited course materials.', available: true },
      { feature: 'No certification upon completion.', available: true },
      { feature: 'Ad-supported platform.', available: true },
      { feature: 'Access to exclusive Pro Plan.', available: true },
      { feature: 'Early access to new courses.', available: true },
    ],
    buttonVariant: 'solid',
    buttonColorScheme: '#0A52A8',
    bgColor: '#FFFFFF',
    textColor: 'black',
    buttonText: '#fff',
  },
];
export const cardsData = [
  {
    id: 1,
    category: 'Guide',
    title: 'A Complete University Application Guide',
    description:
      'This year, we have produced our complete guide to applying to university.',
    date: 'December 19, 2023',
    readTime: '1 min read',
    image: '/images/source.svg',
  },
  {
    id: 2,
    category: 'Chapter',
    title: 'Basic lifeskills for 14-16 year olds',
    description:
      'Summer is a good time to brush up on your life skills. We point you...',
    date: 'July 22, 2022',
    readTime: '1 min read',
    image: '/images/source-2.svg',
  },
  {
    id: 3,
    category: 'Chapter',
    title: 'CV building activities for 16-18 year olds',
    description:
      'We offer advice on activities to build your CV for 16-18 year olds.',
    date: 'July 22, 2022',
    readTime: '2 min read',
    image: '/images/source-3.svg',
  },
  {
    id: 4,
    category: 'Guide',
    title: 'A Complete University Application Guide',
    description:
      'This year, we have produced our complete guide to applying to university.',
    date: 'December 19, 2023',
    readTime: '1 min read',
    image: '/images/source-2.svg',
  },
  {
    id: 5,
    category: 'Chapter',
    title: 'Basic lifeskills for 14-16 year olds',
    description:
      'Summer is a good time to brush up on your life skills. We point you...',
    date: 'July 22, 2022',
    readTime: '1 min read',
    image: '/images/source.svg',
  },
  {
    id: 6,
    category: 'Chapter',
    title: 'CV building activities for 16-18 year olds',
    description:
      'We offer advice on activities to build your CV for 16-18 year olds.',
    date: 'July 22, 2022',
    readTime: '2 min read',
    image: '/images/source-3.svg',
  },
];
